# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 479eb2a843a90f58f55dbbde1d64fcc92014ee69e7da40fd359ab1b6cab2d94560a0067d503b36e5b8b2d8eb9302b21aec4f8d96934ff892a02bdd7a3d3ddb6d

test:
  secret_key_base: 24af1b7e3401428439387aaf019676325b366e71930943cc04440657d6ee3153b7899472843205e8f937b0f889d503662d6233d5ccabb3b3f184868394bc7a51

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
